"""add water stress index table

Revision ID: 04e36c49090e
Revises: e31fe3fbd7ad
Create Date: 2026-08-24 16:41:30.988132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e36c49090e'
down_revision: Union[str, Sequence[str], None] = 'e31fe3fbd7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_stress_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('stress_score', sa.Float(), nullable=False),
    sa.Column('stress_category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.CheckConstraint("stress_category IN ('Low', 'Low-Medium', 'Medium-High', 'High', 'Extremely High')", name='ck_water_stress_category'),
    sa.CheckConstraint('stress_score >= 0 AND stress_score <= 5', name='ck_water_stress_score_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', name='uq_water_stress_state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_stress_index')
    # ### end Alembic commands ###
