"""add methodology coefficients table

Revision ID: 0bc69bacc0d2
Revises: 99f3b858b9d0
Create Date: 2026-08-24 13:17:15.024793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc69bacc0d2'
down_revision: Union[str, Sequence[str], None] = '99f3b858b9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('methodology_coefficients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Enum('on_site', 'operational', 'full_lifecycle', name='scope'), nullable=False),
    sa.Column('ml_per_query', sa.Float(), nullable=False),
    sa.Column('citation_url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint('ml_per_query > 0', name='ck_methodology_ml_per_query_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', name='uq_methodology_source_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('methodology_coefficients')
    sa.Enum(name='scope').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
