"""add facilities and disclosures tables

Revision ID: 2c49c2f95c06
Revises: f08e83c22ff2
Create Date: 2026-08-24 11:28:42.511162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c49c2f95c06'
down_revision: Union[str, Sequence[str], None] = 'f08e83c22ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('withdrawal_gal', sa.Float(), nullable=True),
    sa.Column('consumption_gal', sa.Float(), nullable=True),
    sa.Column('replenishment_pct', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_tier', sa.Enum('peer_reviewed', 'corporate_disclosure', 'modeled_estimate', 'aggregator_estimate', name='source_tier'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'year', name='uq_corporate_disclosure_year')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=True),
    sa.Column('source_tier', sa.Enum('peer_reviewed', 'corporate_disclosure', 'modeled_estimate', 'aggregator_estimate', name='source_tier'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'city', 'country', name='uq_facility_location')
    )
    op.create_table('facility_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('water_withdrawal_l', sa.Float(), nullable=True),
    sa.Column('water_consumption_l', sa.Float(), nullable=True),
    sa.Column('electricity_kwh', sa.Float(), nullable=True),
    sa.Column('pue', sa.Float(), nullable=True),
    sa.Column('wue', sa.Float(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'year', name='uq_facility_metric_year')
    )
    op.create_index(op.f('ix_facility_metrics_facility_id'), 'facility_metrics', ['facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_metrics_facility_id'), table_name='facility_metrics')
    op.drop_table('facility_metrics')
    op.drop_table('facilities')
    op.drop_table('corporate_disclosures')
    sa.Enum(name='source_tier').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
