"""replace facilities with wue stations and readings

Revision ID: 99f3b858b9d0
Revises: 2c49c2f95c06
Create Date: 2026-08-24 11:55:50.555040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99f3b858b9d0'
down_revision: Union[str, Sequence[str], None] = '2c49c2f95c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wue_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'state', name='uq_wue_station_city_state')
    )
    op.create_table('wue_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('onsite_wue', sa.Float(), nullable=True),
    sa.Column('offsite_wue', sa.Float(), nullable=True),
    sa.Column('source_tier', postgresql.ENUM('peer_reviewed', 'corporate_disclosure', 'modeled_estimate', 'aggregator_estimate', name='source_tier', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['wue_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'timestamp', name='uq_wue_reading_timestamp')
    )
    op.create_index(op.f('ix_wue_readings_station_id'), 'wue_readings', ['station_id'], unique=False)
    op.drop_index(op.f('ix_facility_metrics_facility_id'), table_name='facility_metrics')
    op.drop_table('facility_metrics')
    op.drop_table('facilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('capacity_mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_tier', postgresql.ENUM('peer_reviewed', 'corporate_disclosure', 'modeled_estimate', 'aggregator_estimate', name='source_tier', create_type=False), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='facilities_pkey'),
    sa.UniqueConstraint('name', 'city', 'country', name='uq_facility_location', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('facility_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('water_withdrawal_l', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('water_consumption_l', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('electricity_kwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_synthetic', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('facility_metrics_facility_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('facility_metrics_pkey')),
    sa.UniqueConstraint('facility_id', 'year', name=op.f('uq_facility_metric_year'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_facility_metrics_facility_id'), 'facility_metrics', ['facility_id'], unique=False)
    op.drop_index(op.f('ix_wue_readings_station_id'), table_name='wue_readings')
    op.drop_table('wue_readings')
    op.drop_table('wue_stations')
    # ### end Alembic commands ###
