"""add water demand forecasts table

Revision ID: e31fe3fbd7ad
Revises: 0bc69bacc0d2
Create Date: 2026-08-24 16:29:58.625894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31fe3fbd7ad'
down_revision: Union[str, Sequence[str], None] = '0bc69bacc0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_demand_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.Enum('efficiency_improves', 'demand_outpaces', name='forecast_scenario'), nullable=False),
    sa.Column('forecast_year', sa.Integer(), nullable=False),
    sa.Column('predicted_avg_offsite_wue', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('generated_on', sa.Date(), nullable=False),
    sa.CheckConstraint('lower_bound <= predicted_avg_offsite_wue', name='ck_forecast_lower_lte_prediction'),
    sa.CheckConstraint('lower_bound >= 0', name='ck_forecast_lower_nonnegative'),
    sa.CheckConstraint('predicted_avg_offsite_wue <= upper_bound', name='ck_forecast_prediction_lte_upper'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario', 'forecast_year', name='uq_forecast_scenario_year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_demand_forecasts')
    sa.Enum(name='forecast_scenario').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
