"""add energy mix summary table

Revision ID: ef5d55bd5d25
Revises: 035436cd16c4
Create Date: 2026-08-25 12:50:39.625560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5d55bd5d25'
down_revision: Union[str, Sequence[str], None] = '035436cd16c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_mix_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('avg_coal', sa.Float(), nullable=False),
    sa.Column('avg_hydro', sa.Float(), nullable=False),
    sa.Column('avg_natural_gas', sa.Float(), nullable=False),
    sa.Column('avg_nuclear', sa.Float(), nullable=False),
    sa.Column('avg_other', sa.Float(), nullable=False),
    sa.Column('avg_petroleum', sa.Float(), nullable=False),
    sa.Column('avg_solar', sa.Float(), nullable=False),
    sa.Column('avg_wind', sa.Float(), nullable=False),
    sa.Column('pct_renewable', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['wue_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'year', name='uq_energy_mix_station_year')
    )
    op.create_index(op.f('ix_energy_mix_summary_station_id'), 'energy_mix_summary', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_mix_summary_station_id'), table_name='energy_mix_summary')
    op.drop_table('energy_mix_summary')
    # ### end Alembic commands ###
